### ISSUE TITLE
handle SIGWINCH

### ISSUE THREAD

**Issue by llimllib** [nedbat/watchgha#13]
If you resize the terminal, the app just disappears. If it handled the `SIGWINCH` signal, it could redraw itself on resize.

**Comment by nedbat** [comment]
On Mac with iTerm2, resizing doesn't stop the app.  The redraws are a little wonky, and it might take two of them to get everything back where it should be, but it works.  What OS and terminal are you using?

**Comment by llimllib** [comment]
Mac with kitty

**Comment by llimllib** [comment]
I'll provide video in a minute, apologies for the short response, was preparing the PR

**Comment by llimllib** [comment]
Confirmed this behavior happens on iterm2 as well: I get a blank screen between the resize and the next update. 15 seconds can feel like a long time to have a blank screen

**Comment by nedbat** [comment]
Are you saying it waits until the next poll to draw again, or it never draws again?

**Comment by nedbat** [comment]
This is now released as part of [watchgha 2.2.0](https://pypi.org/project/watchgha/2.2.0).
