### ISSUE TITLE
Couldn't find GitHub repo from '.'

### ISSUE THREAD

**Issue by zenspider** [nedbat/watchgha#16]
given a branch configured like so:

```
[branch "mybranch"]
	remote = .
	merge = refs/heads/main
```
(and all of my branches are configured as such (and work fine with other tooling))

it appears that `dulwich.porcelain.get_remote_repo` comes back with `.`.

**Comment by nedbat** [comment]
I haven't seen that before.  What sets `remote = .`?  And what does it mean?

**Comment by zenspider** [comment]
I had to look this up myself:

```
   branch.<name>.remote
       ...

       Additionally, . (a period) is the current local repository
       (a dot-repository), see branch.<name>.merge's final note
       below.

   branch.<name>.merge
       ...

       If you wish to setup git pull so that it merges into <name>
       from another branch in the local repository, you can point
       branch.<name>.merge to the desired branch, and use the
       relative path setting . (a period) for
       branch.<name>.remote.
```

**Comment by zenspider** [comment]
Guessing... if the remote url doesn't resolve via `branch.<name>.remote`, you should fall back to (the python equivalent of):

```
git config "remote.$(git config remote.pushdefault).url"
```

**Comment by nedbat** [comment]
Could you share your full configuration? I don't seem to have `git config remote.pushdefault` defined.

**Comment by zenspider** [comment]
Here's some of it:

```
advice.skippedcherrypicks=true
core.bare=false
core.filemode=true
core.ignorecase=true
core.logallrefupdates=true
core.precomposeunicode=true
core.repositoryformatversion=0
core.untrackedcache=true
feature.manyfiles=true
index.skiphash=false
merge.ours.driver=true
remote.origin.tagopt=--no-tags
remote.origin.url=git@github.com:zendesk/zendesk.git
remote.pushdefault=origin
taggrouping.groups=v:refs/tags/v(?<name>.*)
taggrouping.singles=
```

**Comment by nedbat** [comment]
If this is still happening, can you show the output of `git remote -v`, and possibly the full `.git/config` file? I don't understand how to find a GitHub url from what you have.

**Comment by zenspider** [comment]
It probably still is happening. I don't know. I wrote my own replacement.
