### ISSUE TITLE
Please allow me to watch a single run

### ISSUE THREAD

**Issue by zenspider** [nedbat/watchgha#17]
I use `gh run watch` a lot. The first thing it does is show me the list of running jobs (not just mine, unfortunately). I always focus on the "test" job and ignore all the others. It would be nice if I could do the same thing w/ watchgha, either by specifying the job ID or the job name or via some picker like `gh run watch`. Right now my output that I'm interested in is being drowned out by other jobs.

**Comment by nedbat** [comment]
Added `--only` in 821bc6ca9a145ab00151d9c62a9d0523676136ba.

**Comment by nedbat** [comment]
This is now released as part of [watchgha 2.2.0](https://pypi.org/project/watchgha/2.2.0).
