### ISSUE TITLE
Read repository from git

### ISSUE THREAD

**Issue by adamchainz** [nedbat/watchgha#7]
It would be neat if `watchgha` would pick up the repository URL and branch, without requiring an alias to be created.

**Comment by nedbat** [comment]
This is implemented in ac97dcf8d6b642037efa2d0217f6d25e0c9f6df8.

**Comment by nedbat** [comment]
This is now released as part of [watchgha 2.0.0](https://pypi.org/project/watchgha/2.0.0).
